version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: redis.dockerfile
    restart: "always"
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdb:/var/lib/redis

  celery:
    restart: "always"
    build:
      context: .
      dockerfile: celery.dockerfile
    container_name: celery
    env_file: .env
    command: /venv/bin/celery --app=todo.celery:app worker -B --loglevel=INFO
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - "redis"
      - "postgres"

  postgres:
    container_name: postgres-db
    image: postgres:9.6.6
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8
      - VIRTUAL_HOST=postgres
      - VIRTUAL_PORT=5432

  web:
    container_name: key
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - postgres
    depends_on:
      - 'postgres'
